CREATE SCHEMA IF NOT EXISTS ShoppingList;
USE ShoppingList;

CREATE TABLE IF NOT EXISTS ShoppingList.lists (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id INT UNSIGNED NOT NULL,
	name VARCHAR(50) NOT NULL,
	color VARCHAR(35) NOT NULL,
	created_utc VARCHAR(45) NOT NULL,
	modified_utc VARCHAR(45) NOT NULL,
	PRIMARY KEY (id));
