/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jturner' at '11/29/16 11:20 AM' with Gradle 2.14.1
 *
 * @author jturner, @date 11/29/16 11:20 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
